export interface IStock {
  stockCode: string,
  score: number,
  stockPrice: number,
  patrimonioLiquido: number,
  liquidezCorrente: number,
  ROE: number,
  divSobrePatrimonio: number,
  crescimentoCincoAnos: number,
  precoSobreVP: number,
  precoSobreLucro: number,
  dividendos: number,
  PSR: number,
  precoSobreAtivo: number,
  precoSobreCapitalGiro: number,
  precoSobreEBIT: number,
  precoSobreAtivoCirculante: number,
  EVSobreEBIT: number,
  margemEBIT: number,
  margemLiquida: number,
  ROIC: number,
  liquidezDoisMeses: number,
  timestamp: Date,
}
